#https://stackoverflow.com/questions/53676830/set-up-cpanel-yml-file-to-upload-everything
---
deployment:
  tasks:
    # NOTE: public_html on cPanel must not be removed or renamed.
    # This folder has owner USER:nobody, and the USER user does not have
    # access to change owner. So this folder must stay as-is to keep the nobody
    # group, which is critical to the site working. A new folder won't work.
    - export DEPLOYPATH=/home/emmyther/public_html
    - export REPOPATH=/home/emmyther/repositories/Nanbooru
    # Remove previous old files, if any.
    - /bin/rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory.
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    # Back-up custom files.
    - /bin/bash /home/emmyther/backup/backup.sh
    # Sync repository files to the deploy target path, excluding .git folder.
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH}
    # Run the replacement script.
    #- /bin/bash /home/emmyther/backup/replace.sh    
    # Set correct permissions.
    - /bin/bash /home/emmyther/backup/chmod.sh
#    - /bin/chmod 755 ${DEPLOYPATH}
#    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
#    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
